version: '3'

services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    restart: always
    privileged: true
    hostname: jenkins
    user: root
    ports:
      - "8091:8080"
    environment:
      - JAVA_OPTS="-Dhudson.model.DownloadService.noSignatureCheck=true"
    volumes:
      - "./jenkins:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"

  registry:
    image: registry
    restart: always
    container_name: registry
    hostname: registry
    volumes:
      - ./registry:/var/lib/registry
    ports:
      - "5005:5005"
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5005
